config/routes.rb
  Rails.application.routes.draw do
  resources :pictures
  devise_for :users
  resources :notes do
    get 'message', on: :member
   # resources :posts do
    # resources :comments, only: [create]
    # end
   end
  resources :posts

    root  'posts#index'
    get   'users/:id'  => 'users#show'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord


end

app/models/note.rb
class Note < ApplicationRecord
  has_many :posts
  has_many :users, through: :user_notes
  has_many :user_notes
#   accepts_nested_attributes_for :user_notes
# end

end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :note
  belongs_to :user

  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :posts
  has_many :notes, through: :user_notes
  has_many :user_notes
end

app/models/user_note.rb
class UserNote < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

def after_sign_in_path_for(resource)
   notes_url
end

  def after_sign_out_path_for(resources)
    new_user_session_path
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes= Note.all
    @users= User.all
    @note= Note.new

  end

  def new
   @notes= Note.new
  end

  def create
   @note = Note.new(note_params)
   @note.save
   @notes = Note.all
   redirect_to message_note_path(@note.id)
  end


  def show
  end

  def message
    current_user.notes
    # @posts = Post.all.order("created_at DESC")
    @posts = Post.where(note_id: params[:id]).order("created_at DESC")
    @notes = Note.all
    @user_notes = current_user.notes
    @current_note = Note.find(params[:id])
    @note_id= params[:id]
  end

  private
  def note_params
   # params.require(:note).
   params.require(:note).permit(user_ids: [])
  end


end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
  # params.require(:picture).permit(:date)
  params.require(:picture).permit(:date, :image, :image_cache, :remove_image)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :index, except: :index


  def index
    @posts = Post.all.order("created_at DESC")
    @notes = Note.all
    @user_notes = current_user.notes
    # includes(:user).order("created_at DESC") ここは後で
  end

  def new
    @posts = Post.new
    # @notes = Note.find(params[:format])
  end

  def create
    Post.create(post_params)
     redirect_to message_note_path(params[:post][:note_id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
      if post.user_id == current_user.id
        post.destroy
      end
  end

  def edit
    @posts = Post.find(params[:id])
    @note = @posts.note
  end

  def update
      post = Post.find(params[:id])
     if post.user_id == current_user.id
        post.update(post_params)
     end
     redirect_to message_note_path(params[:post][:note_id])
  end


  def show
    @posts = Post.find(params[:id])
    # @note = @posts.note
    # @note = Note.find(params[:id])
        # @comments = @post.comments.includes(:user)
  end


 private
  def post_params
    params.require(:post).permit(:note_id, :name ,:image, :text).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end


 end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    user = User.find(params[:id])
    @username = user.username
    @posts = user.posts.page(params[:page]).per(5).order("created_at DESC")
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notes</title>
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://code.jquery.com/jquery-3.2.1.js"></script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">

</head>
<body>


<%= yield %>

</body>
</html>

app/views/notes/create.html.erb
<!--   <div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/posts">投稿一覧へ戻る</a>
    </div>
  </div>

 -->
<% form_for ( @notes) do |f| %>

<% end %>

app/views/notes/index.html.erb
<header class="header">
<p>Khôra</p>
 </header>
<div class="background-registrations">
<div class="contents row">
 <div class="chatroom-box">
  <div class="select-chat-user" type="text">
  <h1>Select your buddy</h1>

   <%= form_for(@note) do |f| %>
   <br>
    <%=f.collection_check_boxes :user_ids, @users, :id, :username, checked: [current_user.id] %>
   </br>
    <%= f.submit '決定'  %>
   <% end %>
  </div>
 </div>
</div>
</div>

app/views/notes/message.html.erb
<header class="header" >
 <p>Khôra</p>
</header>

<div class="chat"> <!-- 全体 -->
  <div class="chat-side"> <!-- chat-side 全体 -->
    <div class="chat-user clearfix"> <!--chat上のユーザー -->
      <span class="username">
        <p><%= current_user.username %></p>
      </span>
      <button class="sidebarBtn">
       <span></span>
      </button>
      <div class="chat-user_actions"> <!-- font awesome-->
         <a class="chat-user_action" href="/groups/new">
         </a>
         <a class="chat-user_action" href="/groups/edit">
      <!--     <i class="fa fa-user-o" aria-hidden="true"></i> -->
          </a>
      </div> <!-- chat-user_actions -->
   </div> <!-- chat-user clearfix -->


   <ul class="chat-groups">
        <% @user_notes.each do |note| %>
              <% note.users.each do |user| %>
                <%= render partial: "sidebar/group", locals: { user: user, note: note } %>
              <% end %>
            <% end %>
    <li class="chat-group">
        <a class="chat-group_link" href="/note"> </a>
      <% @notes.each do |note| %>
      <div>
        <a href="/notes/<%= note.id %>"></a>
      </div>
     <% end %> <!-- notes each -->
    </li>
   </ul>
   <div class="calendar" id="MonthCal"></div><!-- カレンダー -->

    <div class="calendar">
      <script type="text/javascript">
       window.onload = googleCalendarSet;
       function googleCalendarSet(){

      var calendarCode1 = '<iframe class="calendar"src="https://calendar.google.com/calendar/embed?';
      var calenderCode2 = '/title=Past%20Posts&amp;height=250&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=6fjl7iph523l52nnoeurpifehc%40group.calendar.google.com&amp;color=%236B3304&amp;ctz=Asia%2FTokyo" style="border-width:0" width="300" height="300" frameborder="0" scrolling="no"></iframe>/'

        document.getElementById("MonthCal").innerHTML = calendarCode1+calenderCode2;
       }
      </script>
    </div>

  </div> <!-- chat side -->

  <div class="chat-main">
   <div class="chat-header clearfix">
    <p><% @current_note.users.each do |user| %>
          <%= user.username unless current_user.id == user.id %>
        <% end %>
    </p>
    <div class="chat-header_left">
         <!-- ?? -->
    </div> <!-- chat-header_left -->

    <div class="chat-header_right">
      <%= link_to "New Post", new_post_path(@note_id), method: "get", class: "chat-header_edit-btn" %>

       <%= link_to "Log out", destroy_user_session_path, method: "delete", class: "chat-header_edit-btn" %>
    </div> <!-- chat-header_right -->
   </div> <!-- chat-header clearfix -->

   <div class="chat-body">
    <% @posts.each do |post| %>
           <div class="message-images">
        <%= image_tag post.image %>
        </div>
     <div class="content-box">
      <div class="username" type="text">
        <span class="name">
         <a href="/users/<%= post.user_id %>">
          <%= post.user.username %>
         </a>
        </span>
      </div>
     <div class="more">
<!--        <div class="message-images">
        <%= image_tag post.image %>
        </div> -->
       <ul class="more_list">
        <li>
         <%= link_to 'See more', "/posts/#{post.id}/", method: :get %>
          <% if user_signed_in? && current_user.id == post.user_id %>
          <% end %>
        </li>
        <li>
         <%= link_to 'Edit', "/posts/#{post.id}/edit", method: :get %>
        </li>
        <li>
         <%= link_to 'Delete', "/posts/#{post.id}", method: :delete %>
        </li>
       </ul>
      </div> <!-- more -->

     <div class="post-content">
       <p><%= post.name %></p>
     </div>
     </div> <!-- content-box -->
    <% end %>
   </div> <!-- chat-body -->
  </div> <!-- chat-main -->
 </div> <!-- chat -->

app/views/pictures/_form.html.erb
<%= form_for(picture) do |f| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

    <!-- 追加個所 -->
  <div class="field">
    <% if @picture.image? %>
      <div class="thumbnail">
      <%= image_tag @picture.image.url %>
    </div>
  <% end %><br>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="field">
    <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
    <% if @picture.persisted? && @picture.image? %>
      <label>
      <%= f.check_box :remove_image %>
      画像を削除
    </label>
  <% end %>
  </div>
  <!-- 追加個所終了 -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.date %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @picture.date %>
</p>

<p>
  <strong>Date:</strong>
  <%= @picture.date %>
</p>

<!-- 追加箇所 開始 -->
<p>
<strong>Image:</strong>
<% if @picture.image? %>
  <div class="thumbnail">
  <%= image_tag @picture.image.url %>
</div>
<% end %>
</p>
<!-- 追加箇所 終了 -->


<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/posts/create.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>

      <a class="btn" href="/posts">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/posts/destroy.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/posts/edit.html.erb
<div class="new-content">
  <%= form_for(@posts) do |f| %>
  <header class="header" >
  <p>Khôra</p>
  </header><!-- /header -->

  <div class="note-box">
    <div class="note-box-inner">
      <div class="body-title">
        <%= f.text_area :name %>
        <%= f.hidden_field :note_id, value: "#{@note.id}" %>
      </div>
      <div class="edit-images">
        <%= image_tag @posts.image %>
        </div>

      <div class="body-wrapper">
        <%= f.text_area :text, class: "inner-wrapper" %>
      </div>
    </div>

    <footer>
      <div class="footer-inner clearfix">
       <div class="footer-inner-float">
        <%= f.submit "Update", class: "content_edit-btn" %>
         <div class="edit-image-button">
         <label style="display: inline">
          <%= f.file_field :image %>
          <%= image_tag "button-48px.png" %>
         </label>
        </div>
       </div>
      </div>
    </footer>
  </div>
  <% end %>
</div>

app/views/posts/index.html.erb
 <div class="chat"> <!-- 全体 -->
  <div class="chat-side"> <!-- chat-side 全体 -->
   <div class="chat-user clearfix"> <!--chat上のユーザー -->
    <span class="username">
      <p><%= current_user.username %></p>
    </span>

    <div class="chat-user_actions"> <!-- font awesome-->
     <a class="chat-user_action" href="/groups/new">
       <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
     </a>
     <a class="chat-user_action" href="/groups/edit">
  <!--     <i class="fa fa-user-o" aria-hidden="true"></i> -->
     </a>
    </div> <!-- chat-user_actions -->
   </div> <!-- chat-user clearfix -->


   <ul class="chat-groups">
        <p><% @user_notes.each do |note| %>
              <% note.users.each do |user| %>
                     <%= link_to "/notes/#{note.id}/message", method: :get do %>  <!-- 数字を表示させたい時はlink_to method 内で数字にしたい場所を#{}にする -->

                <%= user.username unless current_user.id == user.id %>
               <% end %>
              <% end %> <!-- @user_notes.each do |note| -->
            <% end %> <!-- note.users.each do |user| -->
        </p>
    <li class="chat-group">
     <a class="chat-group_link" href="/note"> </a>
      <% @notes.each do |note| %>
      <div>
      <a href="/notes/<%= note.id %>"></a>
      </div>
     <% end %> <!-- notes each -->
    </li>
   </ul>
  </div> <!-- chat side -->
  <div class="chat-body">
    <div class="chat-header clearfix">
    <div class="chat-header_left">
    </div> <!-- chat-header_left -->
    <div class="chat-header_right">
       <%= link_to "ログアウト", destroy_user_session_path, method: "delete", class: "chat-header_edit-btn" %>

    </div> <!-- chat-header_right -->
   </div> <!-- chat-header clearfix -->
  </div><!--  chat-body -->
 </div> <!-- chat -->

app/views/posts/new.html.erb
<header class="header" >
<p>Khôra</p>
</header>

<div class="new-content">
  <%= form_for(@posts) do |f| %>
    <div class="note-box">
      <div class="right-box clearfix">
        <div class="inner-right-box-new">
          <%= f.submit "Post your writing", class: "content_edit-btn" %>
        </div>
        <div class="image-button">
            <label style="display: inline">
              <%= f.file_field :image %>
              <%= image_tag "button-48px.png" %>
            </label>
        </div>
      </div> <!-- right box clearfix -->

     <div class="title-and-body">
      <div class="body-title">
        <%= f.text_area :name, :placeholder => "Title"%>
        <%= f.hidden_field :note_id, value: params[:format] %>
      </div>

<!--      <form action="update.php" method="post" enctype="multipart/form-data">
    <input type="file" name="upfile" size="30" value=""> -->
  </form>
      <div class="body-wrapper">
        <%= f.text_area :text,  class: "inner-wrapper", :placeholder => "Here is the beggining of your journey, enjoy...!" %>
      </div>
    </div>

    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<header class="header" >
<p>Khôra</p>
</header>
 <div class="new-content">
    <div class="note-box">
      <div class="edit-button clearfix">
        <div class="show-right-box">
        <ul style="list-style:none;">
          <li>
         <%= link_to 'Edit Your Post', "/posts/#{@posts.id}/edit", method: :get, class: "chat-header_edit-btn" %>
         </li>
        </ul>
        </div>
      </div>

      <div class="body-title">
        <div class="show-title">
         <p><%= @posts.name %><p>
        </div>
      </div>
       <div class="show-images">
         <%= image_tag @posts.image %>
        </div>

      <div class="body-wrapper">

        <div class="show-post">
         <br><%= simple_format(@posts.text) %></br>
        </div>
      </div>
    </div>
 </div>

app/views/posts/update.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/sidebar/_group.html.erb
<ul class="chat-gorups">
  <li class="chat-group">
    <%= link_to message_note_path(note), class: "chat-group_link" do %>
      <%= user.username unless current_user.id == user.id %>
     <% end %>
  </li>
</ul>